MockServer.Web/Areas/Projects/Models/ProjectAddViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MockServer.Web.Areas.Projects.Models
{
    public class ProjectAddViewModel
    {
        [Required]
        public string Name { get; set; } = string.Empty;
        [Required]
        public string Description { get; set; } = string.Empty;
        public string Owner { get; set; } = string.Empty;
    }
}

MockServer.Web/Areas/Projects/Models/ProjectPaginationQueryResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MockServer.Web.Areas.Projects.Models
{
    public class ProjectPaginationQueryResultViewModel
    {

        public int TotalCount { get; set; } = 0;
        public List<Detail> DetailInfo { get; set; } = null;

        public class Detail
        {
            #region 构造函数
            public Detail()
            {
                Id = 0;
                Name = string.Empty;
                Creator = string.Empty;
                Owner = string.Empty;
                SkyEye = string.Empty;
                State = string.Empty;
                CreateTime = DateTime.Now;
                Url = string.Empty;
                Description = string.Empty;
                ApplyDialogVisible = false;
                IsApply = false;
                EditDialogVisible = false;
                AuditDialogVisible = false;
                IsCanEdit = false;
            }
            #endregion

            public long Id { get; set; }

            public string Name { get; set; }

            public string Creator { get; set; }

            public string Owner { get; set; }

            public string SkyEye { get; set; }

            public string State { get; set; }

            public DateTime CreateTime { get; set; }

            public string Url { get; set; }

            public string Description { get; set; }

            public string CreateTimeStr
            {
                get
                {
                    return CreateTime.ToString();
                }
            }

            /// <summary>
            /// 申请的对话框有效性
            /// </summary>
            public bool ApplyDialogVisible { get; set; }

            /// <summary>
            /// 是否已申请
            /// </summary>
            public bool IsApply { get; set; }

            /// <summary>
            /// 编辑的对话框有效性
            /// </summary>
            public bool EditDialogVisible { get; set; }

            /// <summary>
            /// 审核的对话框有效性
            /// </summary>
            public bool AuditDialogVisible { get; set; }

            /// <summary>
            /// 是否可以编辑
            /// </summary>
            public bool IsCanEdit { get; set; }
        }
    }
}

MockServer.Web/Areas/Projects/Models/ProjectPaginationQueryType.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MockServer.Web.Areas.Projects.Models
{
    public class ProjectPaginationQueryType
    {
        /// <summary>
        /// 已加入
        /// </summary>
        public const string Joined = "Joined";
        /// <summary>
        /// 未加入
        /// </summary>
        public const string UnJoined = "UnJoined";
        /// <summary>
        /// 待审核的
        /// </summary>
        public const string AuditProject = "AuditProject";
        /// <summary>
        /// 部门待申请加入的
        /// </summary>
        public const string DepartmentApply = "DepartmentApply";
    }
}

MockServer.Web/Areas/Projects/Models/ProjectPaginationQueryViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MockServer.Web.Areas.Projects.Models
{
    public class ProjectPaginationQueryViewModel
    {
        /// <summary>
        /// 当前页码
        /// </summary>
        public int CurrentPage { get; set; } = 0;
        /// <summary>
        /// 每页条数
        /// </summary>
        public int PageSize { get; set; } = 0;
        /// <summary>
        /// 全部，已拥有，已加入，未加入
        /// </summary>
        public string Type { get; set; } = string.Empty;
        /// <summary>
        /// 项目名称
        /// </summary>
        public string ProjectName { get; set; } = string.Empty;
    }
}

MockServer.Web/Areas/Projects/Models/ProjectQueryDetailResultViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace MockServer.Web.Areas.Projects.Models
{
    public class ProjectQueryDetailResultViewModel
    {
        #region 构造函数
        public ProjectQueryDetailResultViewModel()
        {
            Id = 0;
            Name = string.Empty;
            Creator = string.Empty;
            Owner = string.Empty;
            SkyEye = string.Empty;
            State = string.Empty;
            CreateTime = new DateTime(1900, 1, 1);
            Url = string.Empty;
            Description = string.Empty;
        }
        #endregion

        public long Id { get; set; }

        public string Name { get; set; }

        public string Creator { get; set; }

        public string Owner { get; set; }

        public string SkyEye { get; set; }

        public string State { get; set; }

        public DateTime CreateTime { get; set; }

        public string Url { get; set; }

        public string Description { get; set; }

        public string CreateTimeStr
        {
            get
            {
                return CreateTime.ToString("yyyy-MM-dd HH:mm");
            }
        }
    }
}

MockServer.Web/Areas/Projects/Models/ProjectUpdateViewModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MockServer.Web.Areas.Projects.Models
{
    public class ProjectUpdateViewModel
    {
        [Required]
        public long Id { get; set; } = 0;
        [Required]
        public string Name { get; set; } = string.Empty;
        [Required]
        public string Description { get; set; } = string.Empty;
    }
}

MockServer.Web/Areas/Admin/Controllers/AuditController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MockServer.Web.Areas.Admin.Controllers
{
    public class AuditController : Controller
    {
        /// <summary>
        /// 项目审核
        /// </summary>
        /// <returns></returns>
        public ActionResult Project()
        {
            return View();
        }

        /// <summary>
        /// 用户组加入审核
        /// </summary>
        /// <returns></returns>
        public ActionResult Permission()
        {
            return View();
        }
    }
}

MockServer.Web/Areas/Projects/Controllers/ApiController.cs
using AutoMapper;
using MockServer.Core.Biz.Projects;
using MockServer.Core.Domain;
using MockServer.Core.Domain.TCFlyMock;
using MockServer.Core.Domain.TCFlyMock.Enums;
using MockServer.Web.Areas.Projects.Models;
using MockServer.Web.Controllers.Filter;
using MockServer.Web.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;

namespace MockServer.Web.Areas.Projects.Controllers
{
    [OAuthorize]
    public class ApiController : Controller
    {
        private IFlightMockProjectBiz FlightMockProjectBiz { get; set; }
        public ApiController(IFlightMockProjectBiz FlightMockProjectBiz)
        {
            this.FlightMockProjectBiz = FlightMockProjectBiz;
        }

        public LyOAuthUserInfo UserInfo
        {
            get
            {
                return CurrentUser();
            }
        }

        #region  Private Method
        private LyOAuthUserInfo CurrentUser()
        {
            var userPrincipal = HttpContext.User as LyOAuthPrincipal;
            var userinfo = userPrincipal.UserData;
            return userinfo;
        }
        #endregion

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult Add(ProjectAddViewModel addModel)
        {
            JsonMessage jsonMsg = new JsonMessage();
            try
            {
                string msg = string.Empty;
                if (ModelState.IsValid)
                {
                    string userInfo = UserInfo.UserName + UserInfo.WorkId;
                    FlightMockProject project = new FlightMockProject()
                    {
                        Description = addModel.Description,
                        Name = addModel.Name.Trim(),
                        Creator = userInfo,
                        Owner = string.IsNullOrWhiteSpace(addModel.Owner) ? userInfo : addModel.Owner,
                        State = MockProjectState.Initialize.ToString()
                    };
                    jsonMsg.Result = FlightMockProjectBiz.Create(project, UserInfo.DepartmentId, out msg);
                    jsonMsg.Message = msg;
                    if (!jsonMsg.Result)
                    {
                        jsonMsg.Type = JsonMessage.MsgType.Error;
                    }
                    return Json(jsonMsg);
                }
                else
                {
                    jsonMsg.Result = false;
                    jsonMsg.Message = "请正确完整输入表单!";
                    jsonMsg.Type = JsonMessage.MsgType.Warn;
                    return Json(jsonMsg);
                }
            }
            catch (Exception ex)
            {
                jsonMsg.Result = false;
                jsonMsg.Message = ex.Message;
                jsonMsg.Type = JsonMessage.MsgType.Error;
                return Json(jsonMsg);
            }
        }

        [HttpPost]
        [ValidateInput(false)]
        public JsonResult Edit(ProjectUpdateViewModel updateModel)
        {
            JsonMessage jsonMsg = new JsonMessage();
            try
            {
                string msg = string.Empty;
                if (ModelState.IsValid)
                {
                    FlightMockProject project = new FlightMockProject()
                    {
                        Id = updateModel.Id,
                        Description = updateModel.Description,
                        Name = updateModel.Name.Trim()
                    };
                    jsonMsg.Result = FlightMockProjectBiz.Edit(project, out msg);
                    jsonMsg.Message = msg;
                    if (!jsonMsg.Result)
                    {
                        jsonMsg.Type = JsonMessage.MsgType.Error;
                    }
                    return Json(jsonMsg);
                }
                else
                {
                    jsonMsg.Result = false;
                    jsonMsg.Message = "请正确完整输入表单!";
                    jsonMsg.Type = JsonMessage.MsgType.Warn;
                    return Json(jsonMsg);
                }
            }
            catch (Exception ex)
            {
                jsonMsg.Result = false;
                jsonMsg.Message = ex.Message;
                jsonMsg.Type = JsonMessage.MsgType.Error;
                return Json(jsonMsg);
            }
        }

        [HttpPost]
        public JsonResult PaginationQuery(ProjectPaginationQueryViewModel viewModel)
        {
            JsonMessage jsonMsg = new JsonMessage();
            try
            {
                IEnumerable<FlightMockProject> result = null;
                ProjectPaginationQueryResultViewModel queryResult = new ProjectPaginationQueryResultViewModel();
                FlightMockProject mockProject = new FlightMockProject() { IsPage = true, PageIndex = viewModel.CurrentPage, PageSize = viewModel.PageSize, State = MockProjectState.Valid.ToString() };
                switch (viewModel.Type)
                {
                    case ProjectPaginationQueryType.Joined:
                        mockProject.CurrentUser = UserInfo.UserName + UserInfo.WorkId;
                        result = FlightMockProjectBiz.QueryByDept(UserInfo.DepartmentId, mockProject);
                        queryResult.TotalCount = FlightMockProjectBiz.QueryCountByDept(UserInfo.DepartmentId, mockProject);
                        break;
                    case ProjectPaginationQueryType.UnJoined:
                        result = FlightMockProjectBiz.UnQueryByDept(UserInfo.DepartmentId, mockProject);
                        queryResult.TotalCount = FlightMockProjectBiz.UnQueryCountByDept(UserInfo.DepartmentId, mockProject);
                        break;
                    case ProjectPaginationQueryType.AuditProject:
                        mockProject.State = MockProjectState.Initialize.ToString();
                        result = FlightMockProjectBiz.Query(mockProject);
                        queryResult.TotalCount = FlightMockProjectBiz.QueryCount(mockProject);
                        break;
                    case ProjectPaginationQueryType.DepartmentApply:
                        mockProject.State = MockProjectState.Initialize.ToString();
                        result = FlightMockProjectBiz.Query(mockProject);
                        queryResult.TotalCount = FlightMockProjectBiz.QueryCount(mockProject);
                        break;
                }
                if (result != null && result.Any())
                {
                    queryResult.DetailInfo = Mapper.Map<List<ProjectPaginationQueryResultViewModel.Detail>>(result);
                    jsonMsg.Data = queryResult;
                    return Json(jsonMsg);
                }
                jsonMsg.Result = false;
                jsonMsg.Type = JsonMessage.MsgType.Warn;
                jsonMsg.Message = "未查询到数据!";
                return Json(jsonMsg);
            }
            catch (Exception ex)
            {
                jsonMsg.Result = false;
                jsonMsg.Message = ex.Message;
                jsonMsg.Type = JsonMessage.MsgType.Error;
                return Json(jsonMsg);
            }
        }

        [HttpGet]
        public JsonResult Detail(long id)
        {
            JsonMessage jsonMsg = new JsonMessage();
            try
            {
                ProjectQueryDetailResultViewModel queryResult = new ProjectQueryDetailResultViewModel();
                var result = FlightMockProjectBiz.Query(id);
                if (result != null)
                {
                    queryResult = Mapper.Map<ProjectQueryDetailResultViewModel>(result);
                }
                jsonMsg.Data = queryResult;
                return Json(jsonMsg, JsonRequestBehavior.AllowGet);
            }
            catch (Exception ex)
            {
                jsonMsg.Result = false;
                jsonMsg.Message = ex.Message;
                jsonMsg.Type = JsonMessage.MsgType.Error;
                return Json(jsonMsg);
            }
        }

        /// <summary>
        /// 审核项目  
        /// </summary>
        /// <param name="id">项目Id</param>
        /// <param name="b">true: 审核通过； false: 驳回</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult Audit(long id, bool b)
        {
            JsonMessage message = new JsonMessage();
            try
            {
                string msg = string.Empty;
                var stage = b ? MockProjectState.Valid.ToString() : MockProjectState.Invalid.ToString();
                var result = FlightMockProjectBiz.UpdateState(id, stage);
                message.Message = b ? "审批成功" : "审批失败";
                message.Result = true;
                message.Type = JsonMessage.MsgType.Info;
            }
            catch (Exception ex)
            {
                message.Message = ex.Message;
                message.Type = JsonMessage.MsgType.Error;
                message.Result = false;
                throw;
            }
            return Json(message);
        }

        /// <summary>
        /// 申请加入指定项目
        /// </summary>
        /// <param name="id">项目id</param>
        /// <returns></returns>
        [HttpPost]
        public JsonResult ApplyJoin(long id)
        {
            JsonMessage jsonMsg = new JsonMessage();
            try
            {
                var result = FlightMockProjectBiz.ApplyJoin(UserInfo.DepartmentId, id);
                jsonMsg.Result = result;
                jsonMsg.Message = result ? "申请成功!" : "申请失败!";
                return Json(jsonMsg);
            }
            catch (Exception ex)
            {
                jsonMsg.Result = false;
                jsonMsg.Message = ex.Message;
                jsonMsg.Type = JsonMessage.MsgType.Error;
                return Json(jsonMsg);
            }
        }
    }
}

MockServer.Web/Areas/Projects/Controllers/PagesController.cs
using MockServer.Web.Controllers.Filter;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MockServer.Web.Areas.Projects.Controllers
{
    [OAuthorize]
    public class PagesController : Controller
    {
        /// <summary>
        /// 项目列表页
        /// </summary>
        /// <returns></returns>
        [OutputCache(Duration = 3600)]
        public ActionResult Index()
        {
            return View();
        }

        /// <summary>
        /// 新增项目
        /// </summary>
        /// <returns></returns>
        [OutputCache(Duration = 3600)]
        public ActionResult Add()
        {
            return View();
        }
    }
}

MockServer.Web/Areas/Admin/Views/Audit/Permission.cshtml
@{
    ViewBag.Title = "用户组权限审核";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


@section pagestyle{
    <link href="~/Content/Themes/css/todo.css" rel="stylesheet" />
}
<div id="app">

    <div class="portlet light col-md-12">
        <div class="portlet-title">
            <div class="caption">
                <i class="fa fa-home font-green-sharp"></i>
                <span class="caption-subject font-green-sharp bold">申请加入模拟系统审核</span>
            </div>
            <div class="tools">
                <a href="javascript:;" class="collapse" data-original-title="" title="">
                </a>
                <a href="#portlet-config" data-toggle="modal" class="config" data-original-title="" title="">
                </a>
                <a href="javascript:;" class="reload" data-original-title="" title="">
                </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-md-12">
                    <el-tabs v-model="activeName" type="card">
                        <el-tab-pane label="待审核" name="DepartmentApply">
                            <div class="todo-tasklist">
                                <div class="todo-tasklist-item todo-tasklist-item-border-green" v-for="(project,index) in projects">
                                    <div class="todo-tasklist-item-title">
                                        {{project.Name}}
                                        <el-dialog title="审核确认" v-model="project.AuditDialogVisible" size="tiny">
                                            <span>【{{project.Owner}}】,申请创建【{{project.Name}}】项目!</span>
                                            <span slot="footer" class="dialog-footer">
                                                <el-button v-on:click="dialogClick(index,false,project.Id)">驳 回</el-button>
                                                <el-button type="primary" v-on:click="dialogClick(index,true,project.Id)">通 过</el-button>
                                            </span>
                                        </el-dialog>
                                        <span class="pull-right"><el-button type="success" size="mini" v-on:click="dialogClick(index,true)">审核</el-button></span>
                                    </div>
                                    <div class="todo-tasklist-item-text">
                                        {{project.Description}}
                                    </div>
                                    <div class="todo-tasklist-controls pull-left">
                                        <el-tag type="gray"><i class="el-icon-date"></i>创建日期:{{project.CreateTimeStr}}</el-tag>
                                        <el-tag type="primary"><i class="fa fa-user"></i>拥有人:{{project.Owner}}</el-tag>
                                    </div>
                                </div>
                            </div>
                        </el-tab-pane>
                    </el-tabs>
                </div>
            </div>
        </div>

        <div class="portlet-body">
            <div v-if="pagination.total===0">
                <div style="float:right">
                    暂无数据!
                </div>
            </div>
            <div v-else>
                <div style="float:right">
                    <el-pagination v-model="pagination"
                                   v-on:current-change="handleCurrentChange"
                                   v-on:size-change="handleSizeChange"
                                   :current-page="pagination.currentPage"
                                   :page-size="pagination.pageSize"
                                   :page-sizes="[5, 10, 15, 20]"
                                   layout="total, sizes, prev, pager, next, jumper"
                                   :total="pagination.total">
                    </el-pagination>
                </div>
            </div>
        </div>
    </div>

</div>

@*<div id="urls" data-auditproject="@Url.Action("DepartmentApply","Api",new { Area="Admin" })"
     data-audit="@Url.Action("PaginationQuery", "Api", new { Area = "Projects" })">
</div>*@
<div id="urls" data-auditproject="@Url.Action("PaginationQuery", "Api", new { Area = "Projects" })"
     data-audit="@Url.Action("DepartmentApply","Api",new { Area="Admin" })">
</div>
@section  scripts{
    <script src="~/Scripts/Admin/departmentApply.js"></script>
    <script>
        jQuery(document).ready(function () {
            departmentApply.init();
        });
    </script>
}

MockServer.Web/Areas/Admin/Views/Audit/Project.cshtml
@{
    ViewBag.Title = "项目审批";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section pagestyle{
    <link href="~/Content/Themes/css/todo.css" rel="stylesheet" />
}
<div id="app">

    <div class="portlet light col-md-12">
        <div class="portlet-title">
            <div class="caption caption-md">
                <span class="caption-subject font-green-sharp bold">项目审核</span>
            </div>
            <div class="actions">
                <a href="javascript:;">
                    <i class="fa fa-plus"></i> 新建项目
                </a>
            </div>
        </div>
        <div class="portlet-body">
            <div class="row">
                <div class="col-md-12">
                    <el-tabs v-model="activeName" type="card">
                        <el-tab-pane label="待审核" name="AuditProject">
                            <div class="todo-tasklist">
                                <div class="todo-tasklist-item todo-tasklist-item-border-green" v-for="(project,index) in projects">
                                    <div class="todo-tasklist-item-title">
                                        {{project.Name}}
                                        <el-dialog title="审核确认"  v-model="project.AuditDialogVisible" size="tiny">
                                            <span>【{{project.Owner}}】,申请创建【{{project.Name}}】项目!</span>
                                            <span slot="footer" class="dialog-footer">
                                                <el-button v-on:click="dialogClick(index,false,project.Id)">驳 回</el-button>
                                                <el-button type="primary" v-on:click="dialogClick(index,true,project.Id)">通 过</el-button>
                                            </span>
                                        </el-dialog>
                                        <span class="pull-right"><el-button type="success" size="mini" v-on:click="dialogClick(index,true)">审核</el-button></span> 
                                    </div>
                                    <div class="todo-tasklist-item-text">
                                        {{project.Description}}
                                    </div>
                                    <div class="todo-tasklist-controls pull-left">
                                        <el-tag type="gray"><i class="el-icon-date"></i>创建日期:{{project.CreateTimeStr}}</el-tag>
                                        <el-tag type="primary"><i class="fa fa-user"></i>拥有人:{{project.Owner}}</el-tag>
                                    </div>
                                </div>
                            </div>
                        </el-tab-pane>
                    </el-tabs>
                </div>
            </div>
        </div>

        <div class="portlet-body">
            <div v-if="pagination.total===0">
                <div style="float:right">
                    暂无数据!
                </div>
            </div>
            <div v-else>
                <div style="float:right">
                    <el-pagination v-model="pagination"
                                   v-on:current-change="handleCurrentChange"
                                   v-on:size-change="handleSizeChange"
                                   :current-page="pagination.currentPage"
                                   :page-size="pagination.pageSize"
                                   :page-sizes="[5, 10, 15, 20]"
                                   layout="total, sizes, prev, pager, next, jumper"
                                   :total="pagination.total">
                    </el-pagination>
                </div>
            </div>
        </div>
    </div>

</div>

<div id="urls" data-auditproject="@Url.Action("PaginationQuery","Api",new {Area="Projects" })"
     data-audit="@Url.Action("Audit", "Api", new { Area = "Projects" })" >
</div>

@section  scripts{
    <script src="~/Scripts/Admin/auditProject.js"></script>
    <script>
        jQuery(document).ready(function () {
            auditProject.init();
        });
    </script>
}